/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, Text } from '@react-three/drei'

export function Model({id, ...props}) {
  const { nodes, materials } = useGLTF('/emoji.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.smile_emoji005.geometry} material={materials.smile} rotation={[0,0.4,0]} scale={0.13} />
      <Text
                position={[0, 0.2, 0]}
                rotation={[0,1.5,0]}
                color="orange"
                anchorX="center"
                anchorY="middle"
                fontSize={0.03}
            >
                {id}
            </Text>
    </group>
  )
}

useGLTF.preload('/emoji.glb')
